project_id = "kobjfrzukzwmexowsfxr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.webhook]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false