workflows:
  ios-release:
    name: iOS Release - MyFitLife
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: MyFitLife CI Key Admin
    
    environment:
      groups:
        - No group
      
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lobato.myfitlife
      
      vars:
        APP_STORE_ID: "6753171808"
      
      node: 20
      xcode: 16.0
      cocoapods: default
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      
      - name: Build web assets
        script: |
          npm run build
      
      - name: Sync Capacitor with iOS
        script: |
          npx cap sync ios
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Increment app version if needed
        script: |
          cd ios/App
          CURRENT_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" App/Info.plist)
          echo "Current version: $CURRENT_VERSION"
          
          # Divide versão em partes
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
          
          if [ -z "$PATCH" ]; then
            PATCH=0
          fi
          
          NEW_PATCH=$(($PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          
          echo "New version: $NEW_VERSION"
          agvtool new-marketing-version $NEW_VERSION

      - name: Increment build number
        script: |
          cd ios/App
          BUILD_NUMBER=$(($BUILD_NUMBER + 1))
          agvtool new-version -all $BUILD_NUMBER
          agvtool new-marketing-version 1.0.1

      
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - lucaslobsoouza@gmail.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: true