workflows:
  ios-build:
    name: Build iOS (App Store)
    max_build_duration: 120
    environment:
      node: 20
      cocoapods: default
      xcode: latest
      vars:
        APP_BUNDLE_ID: com.lobato.myfitlife
        APP_NAME: MyFitLife
        DEVELOPMENT_TEAM: N7379U738N


    integrations:
      app_store_connect: MyFitLife

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps

      - name: Build web (production)
        script: |
          export NODE_ENV=production
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap copy ios
          npx cap sync ios
          if [ -f ios/App/Podfile ]; then
            sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/App/Podfile || true
          fi

      - name: CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Archive with xcodebuild
        script: |
          cd ios/App
          xcodebuild \
          -workspace "App.xcworkspace" \
          -scheme "App" \
          -configuration "Release" \
          -destination "generic/platform=iOS" \
          -archivePath "$CM_BUILD_DIR/App.xcarchive" \
          DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
          PRODUCT_BUNDLE_IDENTIFIER="$APP_BUNDLE_ID" \
          CODE_SIGN_STYLE="Manual"
          clean archive


      - name: Create exportOptions.plist
        script: |
          cat > $CM_BUILD_DIR/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${DEVELOPMENT_TEAM}</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>upload</string>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportOptionsPlist $CM_BUILD_DIR/exportOptions.plist \
            -exportPath $CM_EXPORT_DIR \
            -allowProvisioningUpdates
    signing:
      ios:
        provisioning_profiles:
          - MyFitLife_App_Store.mobileprovision
        certificates:
          - myfitlife.p12

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
