workflows:
  ios-build:
    name: Build iOS (App Store)
    max_build_duration: 120
    environment:
      node: 20
      cocoapods: default
      xcode: latest
      vars:
        APP_BUNDLE_ID: com.lobato.myfitlife
        APP_NAME: MyFitLife
        DEVELOPMENT_TEAM: N7379U738N

    integrations:
      app_store_connect: MyFitLife

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps

      - name: Build web (production)
        script: |
          export NODE_ENV=production
          npm run build

      - name: Regenerate iOS project cleanly
        script: |
          rm -rf ios
          npx cap add ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build and Archive
        script: |
          cd ios/App
          
          # Inicializa keychain temporário
          keychain initialize
          
          # Cria diretórios necessários
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mkdir -p ~/Library/MobileDevice/Certificates
          
          # Copia certificados e perfis para o ambiente
          cp "$CM_BUILD_DIR/myfitlife.p12" ~/Library/MobileDevice/Certificates/
          cp "$CM_BUILD_DIR/MyFitLife_App_Store.mobileprovision" ~/Library/MobileDevice/Provisioning\ Profiles/
          
          # Importa o certificado .p12 para o keychain (sem senha)
          security import ~/Library/MobileDevice/Certificates/myfitlife.p12 -k ~/Library/Keychains/login.keychain-db -T /usr/bin/codesign
          
          # Verifica se o certificado foi adicionado
          echo "Certificados disponíveis:"
          security find-identity -p codesigning -v
          
          # Usa o perfil de provisionamento
          xcode-project use-profiles
          
          # Compila e arquiva
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            clean archive


      - name: Export IPA
        script: |
          cd ios/App
          
          # Obter UUID do provisioning profile
          PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -1)
          PROFILE_UUID=$(grep -aA1 'UUID' "$PROFILE_PATH" | grep -o '[A-Z0-9-]\{36\}' | head -1)
          
          # Obter nome do certificado
          CERT_NAME=$(security find-identity -v -p codesigning | grep "Distribution" | head -1 | sed 's/.*"\(.*\)".*/\1/')
          
          echo "Profile UUID: $PROFILE_UUID"
          echo "Certificate: $CERT_NAME"
          
          # Criar exportOptions.plist com as informações corretas
          cat > /tmp/exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$APP_BUNDLE_ID</key>
                  <string>$PROFILE_UUID</string>
              </dict>
              <key>signingStyle</key>
              <string>manual</string>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          
          # Exportar IPA
          cd "$CM_BUILD_DIR"
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR" \
            -exportOptionsPlist /tmp/exportOptions.plist
          
          echo "IPA criado:"
          ls -lh "$CM_BUILD_DIR"/*.ipa
          