workflows:
  ios-build:
    name: Build iOS (App Store)
    max_build_duration: 120
    environment:
      node: 20
      cocoapods: default
      xcode: latest
      vars:
        APP_BUNDLE_ID: com.lobato.myfitlife
        APP_NAME: MyFitLife
        DEVELOPMENT_TEAM: N7379U738N

    integrations:
      app_store_connect: MyFitLife

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps

      - name: Build web (production)
        script: |
          export NODE_ENV=production
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap copy ios
          npx cap sync ios
          if [ -f ios/App/Podfile ]; then
            sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/App/Podfile || true
          fi

      - name: CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Set up code signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Archive with xcodebuild
        script: |
          cd ios/App
          xcodebuild \
          -workspace "App.xcworkspace" \
          -scheme "App" \
          -configuration "Release" \
          -destination "generic/platform=iOS" \
          -archivePath "$CM_BUILD_DIR/App.xcarchive" \
          CODE_SIGN_STYLE="Manual" \
          clean archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ios/App/exportOptions.plist" \
            -exportPath "$CM_BUILD_DIR" \
            -allowProvisioningUpdates

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true