workflows:
  ios-build:
    name: Build iOS (App Store)
    max_build_duration: 120
    environment:
      node: 20
      cocoapods: default
      xcode: latest
      vars:
        APP_BUNDLE_ID: com.lobato.myfitlife
        APP_NAME: MyFitLife
        DEVELOPMENT_TEAM: N7379U738N

    integrations:
      app_store_connect: MyFitLife

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps

      - name: Build web (production)
        script: |
          export NODE_ENV=production
          npm run build

      - name: Regenerate iOS project cleanly
        script: |
          # Remover iOS antigo completamente
          rm -rf ios
          
          # Criar projeto iOS limpo
          npx cap add ios
          
          # Copiar ícones se existirem
          if [ -f "resources/icon.png" ] || [ -f "public/icon.png" ]; then
            echo "Ícones encontrados, mas precisam ser configurados manualmente depois"
          fi

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build and Archive
        script: |
          cd ios/App
          
          # Configurar assinatura
          keychain initialize
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mkdir -p ~/Library/MobileDevice/Certificates
          cp "$CM_BUILD_DIR/myfitlife.p12" ~/Library/MobileDevice/Certificates/
          cp "$CM_BUILD_DIR/MyFitLife_App_Store.mobileprovision" ~/Library/MobileDevice/Provisioning\ Profiles/
          keychain add-certificates
          xcode-project use-profiles
          
          # Build
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            clean archive