workflows:
  ios-release:
    name: iOS Release - MyFitLife
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    integrations:
      app_store_connect: codemagic
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lobato.myfitlife
      
      vars:
        BUNDLE_ID: "com.lobato.myfitlife"
        APP_STORE_ID: "6753171808"
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
      
      node: 18.17.0
      xcode: 15.0
      cocoapods: default
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      
      - name: Build web assets
        script: |
          npm run build
      
      - name: Sync Capacitor with iOS
        script: |
          npx cap sync ios
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      
      - name: Set build number
        script: |
          cd ios/App
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --config Release
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - lucaslobsoouza@gmail.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
        
      slack:
        channel: '#builds'
        notify_on_build_start: false
        notify:
          success: true
          failure: true