// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcfcvxzwzfczltsxbovd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjZmN2eHp3emZjemx0c3hib3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzU5NTUsImV4cCI6MjA2OTkxMTk1NX0.K42tRjTJ4nrQYoU2Nsn5xO_lc5Himod_kUdxp2IuO9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});